#!/bin/bash
# Dumb script to rebuild docs and push changes to github pages
#
git checkout gh-pages
git merge main
cd docsrc; make github
git commit -a -m "update docs"
git push origin
git checkout main
